Repository axonivy-market/marketplace, pull requests merged in 2024-09, with the labels that each got.

#108 MARP-947 re structure product module content in product
  marketplace-service/src/main/java/com/axonivy/market/assembler/ProductDetailModelAssembler.java
  marketplace-service/src/main/java/com/axonivy/market/constants/EntityConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/MongoDBConstants.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductDetailsController.java
  marketplace-service/src/main/java/com/axonivy/market/entity/Product.java
  marketplace-service/src/main/java/com/axonivy/market/entity/ProductModuleContent.java
  marketplace-service/src/main/java/com/axonivy/market/github/service/impl/GHAxonIvyProductRepoServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/repository/ProductModuleContentRepository.java
  marketplace-service/src/main/java/com/axonivy/market/repository/impl/CustomProductRepositoryImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/util/VersionUtils.java
  marketplace-service/src/test/java/com/axonivy/market/repository/impl/CustomProductRepositoryImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductServiceImplTest.java
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
  marketplace-ui/src/app/shared/pipes/has-value-tab.pipe.ts
Labels: enhancement

#124 MARP-992: Custom dropdown should be scrollable
  marketplace-ui/src/app/shared/components/common-dropdown/common-dropdown.component.scss
  marketplace-ui/src/app/shared/components/common-dropdown/common-dropdown.component.spec.ts
Labels: enhancement

#128 MARP-612 Storing number of downloads version
  marketplace-service/src/main/java/com/axonivy/market/constants/EntityConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/MongoDBConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/RequestMappingConstants.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductDesignerInstallationController.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductDetailsController.java
  marketplace-service/src/main/java/com/axonivy/market/entity/ProductDesignerInstallation.java
  marketplace-service/src/main/java/com/axonivy/market/model/DesignerInstallation.java
  marketplace-service/src/main/java/com/axonivy/market/repository/CustomProductRepository.java
  marketplace-service/src/main/java/com/axonivy/market/repository/ProductDesignerInstallationRepository.java
  marketplace-service/src/main/java/com/axonivy/market/repository/impl/CustomProductRepositoryImpl.java
  marketplace-service/src/main/java/com/axonivy/market/repository/impl/ProductSearchRepositoryImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/ProductDesignerInstallationService.java
  marketplace-service/src/main/java/com/axonivy/market/service/ProductService.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductDesignerInstallationServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
  marketplace-service/src/test/java/com/axonivy/market/BaseSetup.java
  marketplace-service/src/test/java/com/axonivy/market/controller/ProductDesignerInstallationControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/controller/ProductDetailsControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/repository/impl/CustomProductRepositoryImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductDesignerInstallationServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductServiceImplTest.java
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.ts
  marketplace-ui/src/app/modules/product/product.service.spec.ts
  marketplace-ui/src/app/modules/product/product.service.ts
Labels: enhancement

#136 MARP-1016 reduntdant api called
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
  marketplace-ui/src/app/shared/components/common-dropdown/common-dropdown.component.html
  marketplace-ui/src/app/shared/components/common-dropdown/common-dropdown.component.ts
  marketplace-ui/src/app/shared/pipes/active-dropdown-item.pipe.ts
  marketplace-ui/src/app/shared/pipes/missing-readme-content.pipe.ts
Labels: bug

#127 MARP-943 market website detail page of employee onboarding is displayed wrong
  marketplace-service/src/main/java/com/axonivy/market/github/service/GHAxonIvyProductRepoService.java
  marketplace-service/src/main/java/com/axonivy/market/github/service/impl/GHAxonIvyProductRepoServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/util/VersionUtils.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/util/VersionUtilsTest.java
  marketplace-service/src/test/resources/emptySourceUrlMeta.json
  marketplace-ui/src/app/modules/product/product-detail/product-detail-information-tab/product-detail-information-tab.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.scss
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
  marketplace-ui/src/app/shared/enums/product-detail-action-type.ts
  marketplace-ui/src/assets/i18n/de.yaml
  marketplace-ui/src/assets/i18n/en.yaml
Labels: enhancement

#139 MARP-959: AxonIvy Portal Images and URLs are broken
  marketplace-service/src/main/java/com/axonivy/market/comparator/MavenVersionComparator.java
  marketplace-service/src/main/java/com/axonivy/market/config/AsyncConfig.java
  marketplace-service/src/main/java/com/axonivy/market/config/SchedulingConfig.java
  marketplace-service/src/main/java/com/axonivy/market/constants/CommonConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/MavenConstants.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductServiceImplTest.java
Labels: bug

#120 MARP-989: Empty product detail tabs not hidden
  marketplace-ui/src/app/core/services/language/language.service.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
  marketplace-ui/src/app/shared/mocks/mock-data.ts
  marketplace-ui/src/app/shared/models/product-module-content.model.ts
  marketplace-ui/src/app/shared/pipes/has-value-tab.pipe.ts
  marketplace-ui/src/app/shared/pipes/multilingualism.pipe.ts
  marketplace-ui/src/app/shared/utils/common.utils.ts
Labels: enhancement

#132 MARP-1017 Implement Error page
  marketplace-service/src/main/java/com/axonivy/market/enums/ErrorCode.java
  marketplace-service/src/main/java/com/axonivy/market/exceptions/ExceptionHandlers.java
  marketplace-service/src/main/java/com/axonivy/market/exceptions/model/NoContentException.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/FeedbackServiceImpl.java
  marketplace-service/src/test/java/com/axonivy/market/handler/ExceptionHandlersTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/FeedbackServiceImplTest.java
  marketplace-ui/src/app/app.component.spec.ts
  marketplace-ui/src/app/app.component.ts
  marketplace-ui/src/app/app.routes.ts
  marketplace-ui/src/app/core/interceptors/api.interceptor.spec.ts
  marketplace-ui/src/app/core/interceptors/api.interceptor.ts
  marketplace-ui/src/app/shared/components/error-page-component/error-page-component.component.html
  marketplace-ui/src/app/shared/components/error-page-component/error-page-component.component.scss
  marketplace-ui/src/app/shared/components/error-page-component/error-page-component.component.spec.ts
  marketplace-ui/src/app/shared/components/error-page-component/error-page-component.component.ts
  marketplace-ui/src/app/shared/constants/common.constant.ts
  marketplace-ui/src/assets/i18n/de.yaml
  marketplace-ui/src/assets/i18n/en.yaml
  marketplace-ui/src/assets/images/misc/robot-black.png
  marketplace-ui/src/assets/images/misc/robot-mobile-black.png
  marketplace-ui/src/assets/images/misc/robot-mobile.png
  marketplace-ui/src/assets/images/misc/robot.png
  marketplace-ui/src/assets/scss/custom-style.scss
Labels: enhancement

#135 update CI build
  .github/workflows/service-ci-build.yml
  .github/workflows/ui-ci-build.yml
Labels: bug

#141 MARP-1040 Remove Industry attribute from UI
  marketplace-ui/src/app/modules/product/product-detail/product-detail-information-tab/product-detail-information-tab.component.html
  marketplace-ui/src/assets/i18n/de.yaml
  marketplace-ui/src/assets/i18n/en.yaml
Labels: enhancement

#126 MARP-990: Fix download dialog position
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.scss
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.ts
Labels: enhancement

#148 MARP-1068 remove check header for GET request
  marketplace-build/.env
  marketplace-build/dev/.env
  marketplace-build/dev/docker-compose.yml
  marketplace-build/docker-compose.yml
  marketplace-build/release/.env
  marketplace-build/release/docker-compose.yml
  marketplace-service/pom.xml
  marketplace-service/src/main/java/com/axonivy/market/config/MarketHeaderInterceptor.java
  marketplace-service/src/main/resources/application.properties
  marketplace-ui/src/app/core/interceptors/api.interceptor.ts
Labels: enhancement

#147 Bugfix/marp 1062 product module content got duplicated after several syncs
  marketplace-service/src/main/java/com/axonivy/market/assembler/ProductDetailModelAssembler.java
  marketplace-service/src/main/java/com/axonivy/market/constants/CommonConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/MongoDBConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/RequestMappingConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/RequestParamConstants.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductDesignerInstallationController.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductDetailsController.java
  marketplace-service/src/main/java/com/axonivy/market/entity/GitHubRepoMeta.java
  marketplace-service/src/main/java/com/axonivy/market/entity/Product.java
  marketplace-service/src/main/java/com/axonivy/market/entity/ProductDesignerInstallation.java
  marketplace-service/src/main/java/com/axonivy/market/entity/ProductJsonContent.java
  marketplace-service/src/main/java/com/axonivy/market/entity/ProductModuleContent.java
  marketplace-service/src/main/java/com/axonivy/market/exceptions/model/NotFoundException.java
  marketplace-service/src/main/java/com/axonivy/market/factory/ProductFactory.java
  marketplace-service/src/main/java/com/axonivy/market/github/service/impl/GHAxonIvyProductRepoServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/github/service/impl/GitHubServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/github/util/GitHubUtils.java
  marketplace-service/src/main/java/com/axonivy/market/repository/CustomProductModuleContentRepository.java
  marketplace-service/src/main/java/com/axonivy/market/repository/CustomRepository.java
  marketplace-service/src/main/java/com/axonivy/market/repository/ProductJsonContentRepository.java
  marketplace-service/src/main/java/com/axonivy/market/repository/ProductModuleContentRepository.java
  marketplace-service/src/main/java/com/axonivy/market/repository/impl/CustomProductModuleContentRepositoryImpl.java
  marketplace-service/src/main/java/com/axonivy/market/repository/impl/CustomProductRepositoryImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/util/VersionUtils.java
  marketplace-service/src/test/java/com/axonivy/market/factory/ProductFactoryTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductServiceImplTest.java
Labels: bug

#140 MARP-1059 market website rating does not work after login
  marketplace-service/src/main/java/com/axonivy/market/constants/CommonConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/ErrorMessageConstants.java
  marketplace-service/src/main/java/com/axonivy/market/controller/OAuth2Controller.java
  marketplace-service/src/main/java/com/axonivy/market/github/service/impl/GitHubServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/github/util/GitHubUtils.java
  marketplace-service/src/test/java/com/axonivy/market/controller/OAuth2ControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/handler/ExceptionHandlersTest.java
  marketplace-service/src/test/java/com/axonivy/market/util/GitHubUtilsTest.java
Labels: bug

#142 MARP-1021 Layout broken in the scale 50%
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.scss
Labels: enhancement

#145 MARP-1014: Product detail tabs
  marketplace-ui/src/app/modules/product/product-detail/product-detail-maven-content/product-detail-maven-content.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail-maven-content/product-detail-maven-content.component.scss
  marketplace-ui/src/app/modules/product/product-detail/product-detail-maven-content/product-detail-maven-content.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-maven-content/product-detail-maven-content.component.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.html
Labels: bug

#149 MARP-1026 Amazon Lex missing some part of description
  marketplace-service/src/main/java/com/axonivy/market/github/service/impl/GHAxonIvyProductRepoServiceImpl.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/GHAxonIvyProductRepoServiceImplTest.java
Labels: enhancement

#146 Feature/marp 1058 market website remove using of images url from GitHub in product detail
  marketplace-service/src/main/java/com/axonivy/market/assembler/ProductDetailModelAssembler.java
  marketplace-service/src/main/java/com/axonivy/market/assembler/ProductModelAssembler.java
  marketplace-service/src/main/java/com/axonivy/market/config/WebConfig.java
  marketplace-service/src/main/java/com/axonivy/market/constants/CommonConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/EntityConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/ProductJsonConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/RequestMappingConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/RequestParamConstants.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ImageController.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductDetailsController.java
  marketplace-service/src/main/java/com/axonivy/market/entity/Image.java
  marketplace-service/src/main/java/com/axonivy/market/entity/Product.java
  marketplace-service/src/main/java/com/axonivy/market/factory/ProductFactory.java
  marketplace-service/src/main/java/com/axonivy/market/github/service/impl/GHAxonIvyProductRepoServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/github/util/GitHubUtils.java
  marketplace-service/src/main/java/com/axonivy/market/repository/ImageRepository.java
  marketplace-service/src/main/java/com/axonivy/market/repository/ProductRepository.java
  marketplace-service/src/main/java/com/axonivy/market/service/ImageService.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ImageServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/util/ImageUtils.java
  marketplace-service/src/test/java/com/axonivy/market/assembler/ProductDetailModelAssemblerTest.java
  marketplace-service/src/test/java/com/axonivy/market/controller/ImageControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/controller/ProductDetailsControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/factory/ProductFactoryTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/GHAxonIvyProductRepoServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ImageServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/VersionServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/util/GitHubUtilsTest.java
  marketplace-service/src/test/java/com/axonivy/market/util/ImageUtilsTest.java
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
Labels: enhancement

#134 MARP-1015: Navbar menu in mobile mode
  marketplace-ui/src/app/app.component.html
  marketplace-ui/src/app/app.component.scss
  marketplace-ui/src/app/app.component.spec.ts
  marketplace-ui/src/app/app.component.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.scss
  marketplace-ui/src/app/shared/components/footer/footer.component.html
  marketplace-ui/src/app/shared/components/header/header.component.scss
  marketplace-ui/src/app/shared/components/header/header.component.ts
  marketplace-ui/src/app/shared/components/header/navigation/navigation.component.html
  marketplace-ui/src/app/shared/components/header/navigation/navigation.component.scss
  marketplace-ui/src/app/shared/components/header/navigation/navigation.component.spec.ts
  marketplace-ui/src/app/shared/components/header/navigation/navigation.component.ts
  marketplace-ui/src/app/shared/components/header/search-bar/search-bar.component.html
  marketplace-ui/src/app/shared/components/header/search-bar/search-bar.component.spec.ts
  marketplace-ui/src/assets/i18n/de.yaml
  marketplace-ui/src/assets/i18n/en.yaml
Labels: enhancement

#155 MARP-950: rest client navigate incorrectly in ai designer
  marketplace-ui/src/app/modules/product/product.component.spec.ts
  marketplace-ui/src/app/modules/product/product.component.ts
Labels: bug

#158 MARP-1015: Fix sonar
  marketplace-ui/src/app/app.component.ts
  marketplace-ui/src/app/shared/components/header/header.component.ts
Labels: enhancement

#160 Marp-1100 market website error occurring after choosing snapshot version
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
Labels: bug

#159 Feature/marp 1058 market website remove using of images url from GitHub in product detail
  marketplace-ui/src/app/modules/product/product-card/product-card.component.html
  marketplace-ui/src/app/modules/product/product-card/product-card.component.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.scss
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
  marketplace-ui/src/app/shared/constants/common.constant.ts
  marketplace-ui/src/app/shared/pipes/logo.pipe.ts
Labels: enhancement

#162 MARP-1104 Market website portal versions and artifacts aren t shown marketplace website
  marketplace-service/src/main/java/com/axonivy/market/enums/NonStandardProduct.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/VersionServiceImpl.java
Labels: bug

#161 Bug/fix/marp 1067 marketplace website can not download install artifact snapshot
  marketplace-service/src/main/java/com/axonivy/market/comparator/ArchivedArtifactsComparator.java
  marketplace-service/src/main/java/com/axonivy/market/comparator/LatestVersionComparator.java
  marketplace-service/src/main/java/com/axonivy/market/comparator/MavenVersionComparator.java
  marketplace-service/src/main/java/com/axonivy/market/constants/MavenConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/ProductJsonConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/RequestMappingConstants.java
  marketplace-service/src/main/java/com/axonivy/market/entity/MavenArtifactVersion.java
  marketplace-service/src/main/java/com/axonivy/market/github/service/GHAxonIvyProductRepoService.java
  marketplace-service/src/main/java/com/axonivy/market/github/service/impl/GHAxonIvyProductRepoServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/VersionService.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/VersionServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/util/VersionUtils.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/VersionServiceImplTest.java
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.ts
Labels: bug

#169 Feature/format3
  marketplace-service/.editorconfig
  marketplace-service/src/main/java/com/axonivy/market/controller/FeedbackController.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ImageController.java
  marketplace-service/src/main/java/com/axonivy/market/controller/OAuth2Controller.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductController.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductDesignerInstallationController.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductDetailsController.java
  marketplace-service/src/main/java/com/axonivy/market/entity/Image.java
  marketplace-service/src/main/java/com/axonivy/market/entity/MavenArtifactModel.java
  marketplace-service/src/main/java/com/axonivy/market/entity/ProductModuleContent.java
  marketplace-service/src/main/java/com/axonivy/market/enums/NonStandardProduct.java
  marketplace-service/src/main/java/com/axonivy/market/model/ProductDetailModel.java
  marketplace-service/src/main/java/com/axonivy/market/model/ProductModel.java
  marketplace-service/src/main/java/com/axonivy/market/repository/ProductRepository.java
  marketplace-service/src/test/java/com/axonivy/market/controller/ProductDesignerInstallationControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/controller/ProductDetailsControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/GHAxonIvyProductRepoServiceImplTest.java
Labels: enhancement

#171 fix sonar
  marketplace-service/src/test/java/com/axonivy/market/service/impl/GHAxonIvyProductRepoServiceImplTest.java
Labels: enhancement, skip-changelog

#129 MARP-994: Market-website-Artifact-and-version-in-download-feature-not save-update
  marketplace-ui/src/app/app.component.html
  marketplace-ui/src/app/app.component.scss
  marketplace-ui/src/app/app.component.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-feedback/show-feedbacks-dialog/show-feedbacks-dialog.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
  marketplace-ui/src/app/modules/product/product.service.spec.ts
  marketplace-ui/src/app/modules/product/product.service.ts
  marketplace-ui/src/app/shared/components/header/search-bar/search-bar.component.spec.ts
  marketplace-ui/src/app/shared/components/loading-spinner/loading-spinner.component.html
  marketplace-ui/src/app/shared/components/loading-spinner/loading-spinner.component.scss
  marketplace-ui/src/app/shared/components/loading-spinner/loading-spinner.component.spec.ts
  marketplace-ui/src/app/shared/components/loading-spinner/loading-spinner.component.ts
  marketplace-ui/src/app/shared/pipes/icon.pipe.spec.ts
  marketplace-ui/src/app/shared/utils/common-utils.spec.ts
  marketplace-ui/src/app/shared/utils/common.utils.ts
Labels: enhancement

#170 MARP-1114: Wrong documentation for doc-factory
  marketplace-service/src/main/java/com/axonivy/market/enums/NonStandardProduct.java
  marketplace-service/src/main/java/com/axonivy/market/github/service/impl/GHAxonIvyProductRepoServiceImpl.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/GHAxonIvyProductRepoServiceImplTest.java
  marketplace-ui/src/app/modules/product/product.component.html
Labels: bug

#165 Bugfix/marp 1123 market website images of new connector skribble can not be displayed
  marketplace-service/src/main/java/com/axonivy/market/repository/ImageRepository.java
  marketplace-service/src/main/java/com/axonivy/market/repository/ProductRepository.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductServiceImplTest.java
Labels: bug

#164 MARP-1125 Get images using recursive
  marketplace-service/src/main/java/com/axonivy/market/github/service/impl/GHAxonIvyProductRepoServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/github/util/GitHubUtils.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/GHAxonIvyProductRepoServiceImplTest.java
Labels: bug

#174 MARP-1148 Fix wrong download dialog display in detail page
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.scss
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.html
Labels: bug

#173 MARP-1092 Show real error code in error page
  marketplace-ui/src/app/app.routes.ts
  marketplace-ui/src/app/core/interceptors/api.interceptor.ts
  marketplace-ui/src/app/shared/components/error-page/error-page.component.html
  marketplace-ui/src/app/shared/components/error-page/error-page.component.scss
  marketplace-ui/src/app/shared/components/error-page/error-page.component.spec.ts
  marketplace-ui/src/app/shared/components/error-page/error-page.component.ts
  marketplace-ui/src/app/shared/constants/common.constant.ts
  marketplace-ui/src/assets/i18n/de.yaml
  marketplace-ui/src/assets/i18n/en.yaml
Labels: enhancement

#178 MARP-1175 Add null check for finding product detail
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductDetailsController.java
  marketplace-service/src/test/java/com/axonivy/market/controller/ProductDetailsControllerTest.java
Labels: bug

#177 MARP-1174 Fix various styling issues of buttons and dropdowns
  marketplace-ui/src/app/core/interceptors/api.interceptor.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.scss
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.scss
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.spec.ts
  marketplace-ui/src/app/shared/components/common-dropdown/common-dropdown.component.html
Labels: bug

#176 MARP-1169 Broken URLs for footer
  marketplace-ui/src/app/shared/components/footer/footer.component.html
  marketplace-ui/src/app/shared/components/footer/footer.component.spec.ts
  marketplace-ui/src/app/shared/components/footer/footer.component.ts
  marketplace-ui/src/app/shared/constants/common.constant.ts
  marketplace-ui/src/assets/i18n/de.yaml
  marketplace-ui/src/assets/i18n/en.yaml
Labels: bug
