Repository axonivy-market/marketplace, pull requests merged in 2024-08, with the labels that each got.

#107 MARP-620 Add release-drafter workflow
  .github/workflows/release-drafter.yml
Labels: enhancement, skip-changelog

#112 MARP-620 Add publish-release workflow
  .github/workflows/publish-release.yml
  .github/workflows/release-drafter.yml
Labels: enhancement, skip-changelog

#117 Feature/marp 760 open marketplace from within designer install item
  marketplace-service/src/main/java/com/axonivy/market/assembler/ProductDetailModelAssembler.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductDetailsController.java
  marketplace-service/src/main/java/com/axonivy/market/entity/Product.java
  marketplace-service/src/main/java/com/axonivy/market/model/ProductDetailModel.java
  marketplace-service/src/main/java/com/axonivy/market/model/VersionAndUrlModel.java
  marketplace-service/src/main/java/com/axonivy/market/service/VersionService.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/VersionServiceImpl.java
  marketplace-service/src/test/java/com/axonivy/market/assembler/ProductDetailModelAssemblerTest.java
  marketplace-service/src/test/java/com/axonivy/market/controller/ProductDetailsControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/VersionServiceImplTest.java
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
  marketplace-ui/src/app/modules/product/product.service.spec.ts
  marketplace-ui/src/app/modules/product/product.service.ts
  marketplace-ui/src/app/shared/components/common-dropdown/common-dropdown.component.html
  marketplace-ui/src/app/shared/components/common-dropdown/common-dropdown.component.ts
  marketplace-ui/src/app/shared/models/item-dropdown.model.ts
  marketplace-ui/src/app/shared/models/product-detail.model.ts
  marketplace-ui/src/app/shared/models/version-and-url.ts
Labels: enhancement

#122 MARP-1011 Can not load next product batch in Landingpage of SprintRelease
  marketplace-build/config/nginx/nginx.conf
  marketplace-build/release/docker-compose.yml
  marketplace-ui/package-lock.json
Labels: bug
