Repository axonivy-market/marketplace, pull requests merged in 2025-03, with the labels that each got.

#312 MARP-2085 The latest tag does not label the latest release
  marketplace-service/src/main/java/com/axonivy/market/assembler/GithubReleaseModelAssembler.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductDetailsController.java
  marketplace-service/src/main/java/com/axonivy/market/github/service/GitHubService.java
  marketplace-service/src/main/java/com/axonivy/market/github/service/impl/GitHubServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/model/GitHubReleaseModel.java
  marketplace-service/src/main/java/com/axonivy/market/service/ProductService.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
  marketplace-service/src/test/java/com/axonivy/market/assembler/GitHubReleaseModelAssemblerTest.java
  marketplace-service/src/test/java/com/axonivy/market/controller/ProductControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/controller/ProductDetailsControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/SystemTasksTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/GitHubServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductServiceImplTest.java
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
  marketplace-ui/src/app/shared/mocks/mock-data.ts
  marketplace-ui/src/app/shared/models/apis/product-release.model.ts
  marketplace-ui/src/app/shared/models/product-release-safe-html.model.ts
Labels: bug

#313 MARP-2085 The latest tag does not label the latest release
  marketplace-service/src/main/java/com/axonivy/market/github/service/impl/GitHubServiceImpl.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/GitHubServiceImplTest.java
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
  marketplace-ui/src/app/modules/product/product.service.spec.ts
  marketplace-ui/src/app/modules/product/product.service.ts
  marketplace-ui/src/app/shared/mocks/mock-data.ts
  marketplace-ui/src/app/shared/models/apis/product-releases-response.model.ts
Labels: bug

#315 MARP-2124 Handle issues before new release 1.10.0
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductDetailsController.java
  marketplace-service/src/main/java/com/axonivy/market/model/GitHubReleaseModel.java
  marketplace-service/src/main/java/com/axonivy/market/model/ProductDetailModel.java
  marketplace-service/src/main/java/com/axonivy/market/schedulingtask/ScheduledTasks.java
  marketplace-service/src/main/java/com/axonivy/market/util/VersionUtils.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/FileDownloadServiceImplTest.java
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
  marketplace-ui/src/app/shared/models/product-release-safe-html.model.ts
Labels: bug

#314 MARP-2124 Create release 1.10.0
  marketplace-service/pom.xml
  marketplace-service/src/main/java/com/axonivy/market/MarketplaceServiceApplication.java
  marketplace-service/src/main/java/com/axonivy/market/assembler/FeedbackModelAssembler.java
  marketplace-service/src/main/java/com/axonivy/market/assembler/GithubReleaseModelAssembler.java
  marketplace-service/src/main/java/com/axonivy/market/assembler/ProductDetailModelAssembler.java
  marketplace-service/src/main/java/com/axonivy/market/assembler/ProductModelAssembler.java
  marketplace-service/src/main/java/com/axonivy/market/config/CaffeineCacheConfig.java
  marketplace-service/src/main/java/com/axonivy/market/constants/RequestMappingConstants.java
  marketplace-service/src/main/java/com/axonivy/market/controller/FeedbackController.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductDetailsController.java
  marketplace-service/src/main/java/com/axonivy/market/github/service/GitHubService.java
  marketplace-service/src/main/java/com/axonivy/market/github/service/impl/GitHubServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/github/util/GitHubUtils.java
  marketplace-service/src/main/java/com/axonivy/market/model/GitHubReleaseModel.java
  marketplace-service/src/main/java/com/axonivy/market/model/ProductDetailModel.java
  marketplace-service/src/main/java/com/axonivy/market/model/ProductModel.java
  marketplace-service/src/main/java/com/axonivy/market/schedulingtask/ScheduledTasks.java
  marketplace-service/src/main/java/com/axonivy/market/service/ProductService.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/VersionServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/util/MavenUtils.java
  marketplace-service/src/main/java/com/axonivy/market/util/MetadataReaderUtils.java
  marketplace-service/src/main/java/com/axonivy/market/util/VersionUtils.java
  marketplace-service/src/test/java/com/axonivy/market/assembler/GitHubReleaseModelAssemblerTest.java
  marketplace-service/src/test/java/com/axonivy/market/assembler/ProductDetailMavenArtifactModelAssemblerTest.java
  marketplace-service/src/test/java/com/axonivy/market/controller/ProductControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/controller/ProductDetailsControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/SystemTasksTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/FileDownloadServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/GitHubServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/SchedulingTasksTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/VersionServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/util/GitHubUtilsTest.java
  marketplace-service/src/test/java/com/axonivy/market/util/MavenUtilsTest.java
  marketplace-service/src/test/java/com/axonivy/market/util/MetadataReaderUtilsTest.java
  marketplace-service/src/test/resources/snapshotMetadata.xml
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.scss
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
  marketplace-ui/src/app/modules/product/product-filter/product-filter.component.html
  marketplace-ui/src/app/modules/product/product-filter/product-filter.component.scss
  marketplace-ui/src/app/modules/product/product.service.spec.ts
  marketplace-ui/src/app/modules/product/product.service.ts
  marketplace-ui/src/app/modules/release-preview/release-preview.component.ts
  marketplace-ui/src/app/shared/components/error-page/error-page.component.html
  marketplace-ui/src/app/shared/components/error-page/error-page.component.scss
  marketplace-ui/src/app/shared/mocks/mock-data.ts
  marketplace-ui/src/app/shared/mocks/mock-services.ts
  marketplace-ui/src/app/shared/models/apis/product-release.model.ts
  marketplace-ui/src/app/shared/models/apis/product-releases-response.model.ts
  marketplace-ui/src/app/shared/models/product-release-safe-html.model.ts
  marketplace-ui/src/app/shared/models/product.model.ts
  marketplace-ui/src/app/shared/services/markdown.service.spec.ts
  marketplace-ui/src/app/shared/services/markdown.service.ts
  marketplace-ui/src/assets/i18n/de.yaml
  marketplace-ui/src/assets/i18n/en.yaml
Labels: skip-changelog

#302 MARP-1975 Approval step for comments in marketplace
  marketplace-service/src/main/java/com/axonivy/market/assembler/FeedbackModelAssembler.java
  marketplace-service/src/main/java/com/axonivy/market/constants/MongoDBConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/RequestMappingConstants.java
  marketplace-service/src/main/java/com/axonivy/market/controller/FeedbackController.java
  marketplace-service/src/main/java/com/axonivy/market/controller/OAuth2Controller.java
  marketplace-service/src/main/java/com/axonivy/market/entity/Feedback.java
  marketplace-service/src/main/java/com/axonivy/market/enums/FeedbackStatus.java
  marketplace-service/src/main/java/com/axonivy/market/model/FeedbackApprovalModel.java
  marketplace-service/src/main/java/com/axonivy/market/model/FeedbackModel.java
  marketplace-service/src/main/java/com/axonivy/market/repository/FeedbackRepository.java
  marketplace-service/src/main/java/com/axonivy/market/service/FeedbackService.java
  marketplace-service/src/main/java/com/axonivy/market/service/JwtService.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/FeedbackServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/JwtServiceImpl.java
  marketplace-service/src/test/java/com/axonivy/market/BaseSetup.java
  marketplace-service/src/test/java/com/axonivy/market/controller/FeedbackControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/controller/OAuth2ControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/FeedbackServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/JwtServiceImplTest.java
  marketplace-ui/src/app/app.routes.ts
  marketplace-ui/src/app/auth/auth.service.ts
  marketplace-ui/src/app/modules/feedback-approval/feedback-approval.component.html
  marketplace-ui/src/app/modules/feedback-approval/feedback-approval.component.scss
  marketplace-ui/src/app/modules/feedback-approval/feedback-approval.component.spec.ts
  marketplace-ui/src/app/modules/feedback-approval/feedback-approval.component.ts
  marketplace-ui/src/app/modules/feedback-approval/feedback-table/feedback-table.component.html
  marketplace-ui/src/app/modules/feedback-approval/feedback-table/feedback-table.component.scss
  marketplace-ui/src/app/modules/feedback-approval/feedback-table/feedback-table.component.spec.ts
  marketplace-ui/src/app/modules/feedback-approval/feedback-table/feedback-table.component.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-feedback/product-feedbacks-panel/product-feedback.service.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-feedback/product-feedbacks-panel/product-feedback.service.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-feedback/product-feedbacks-panel/product-feedback/product-feedback.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail-feedback/product-feedbacks-panel/product-feedback/product-feedback.component.scss
  marketplace-ui/src/app/modules/product/product-detail/product-detail-feedback/product-feedbacks-panel/product-feedback/product-feedback.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-feedback/product-feedbacks-panel/product-feedback/product-feedback.component.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-feedback/product-feedbacks-panel/product-feedbacks-panel.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail-feedback/product-star-rating-panel/add-feedback-dialog/add-feedback-dialog.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail-feedback/product-star-rating-panel/add-feedback-dialog/add-feedback-dialog.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-feedback/product-star-rating-panel/add-feedback-dialog/add-feedback-dialog.component.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-feedback/product-star-rating-panel/add-feedback-dialog/success-dialog/success-dialog.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail-feedback/product-star-rating-panel/add-feedback-dialog/success-dialog/success-dialog.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
  marketplace-ui/src/app/modules/security-monitor/security-monitor.component.ts
  marketplace-ui/src/app/shared/components/star-rating/star-rating.component.html
  marketplace-ui/src/app/shared/components/star-rating/star-rating.component.ts
  marketplace-ui/src/app/shared/constants/api.constant.ts
  marketplace-ui/src/app/shared/constants/common.constant.ts
  marketplace-ui/src/app/shared/enums/feedback-status.enum.ts
  marketplace-ui/src/app/shared/mocks/mock-data.ts
  marketplace-ui/src/app/shared/models/feedback.model.ts
  marketplace-ui/src/assets/i18n/de.yaml
  marketplace-ui/src/assets/i18n/en.yaml
  marketplace-ui/src/assets/scss/custom-modal-style.scss
  marketplace-ui/src/assets/scss/custom-style.scss
  marketplace-ui/src/environments/environment.development.ts
  marketplace-ui/src/environments/environment.staging.ts
  marketplace-ui/src/environments/environment.ts
Labels: enhancement

#305 MARP-2083: Add-version-to-filename-for-zip-artifact
  marketplace-service/src/main/java/com/axonivy/market/constants/MavenConstants.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductDetailsController.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/MavenDependencyServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductContentServiceImpl.java
  marketplace-service/src/test/java/com/axonivy/market/BaseSetup.java
  marketplace-service/src/test/java/com/axonivy/market/controller/ProductDetailsControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/MavenDependencyServiceImplTest.java
Labels: enhancement

#316 MARP-2019 Switch to a new DB for marketplace server
  .github/workflows/docker-build.yml
Labels: enhancement

#317 MARP-2112 Update docker compose file
  .github/workflows/docker-build.yml
  marketplace-build/docker-compose.yml
Labels: enhancement

#320 Marp 2181 marketplace handle sonar in develop branch
  marketplace-service/src/main/java/com/axonivy/market/entity/ArchivedArtifact.java
  marketplace-service/src/main/java/com/axonivy/market/entity/Artifact.java
  marketplace-service/src/main/java/com/axonivy/market/entity/Product.java
  marketplace-service/src/main/java/com/axonivy/market/factory/ProductFactory.java
  marketplace-service/src/main/java/com/axonivy/market/github/model/Meta.java
  marketplace-service/src/main/java/com/axonivy/market/github/util/GitHubUtils.java
  marketplace-service/src/main/java/com/axonivy/market/repository/ArtifactRepository.java
  marketplace-service/src/main/java/com/axonivy/market/repository/impl/CustomProductRepositoryImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/ImageService.java
  marketplace-service/src/main/java/com/axonivy/market/service/MetadataService.java
  marketplace-service/src/main/java/com/axonivy/market/service/ProductContentService.java
  marketplace-service/src/main/java/com/axonivy/market/service/ProductService.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ExternalDocumentServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ImageServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/MavenDependencyServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/MetadataServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductContentServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/VersionServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/util/MavenUtils.java
  marketplace-service/src/main/java/com/axonivy/market/util/MetadataReaderUtils.java
  marketplace-service/src/main/java/com/axonivy/market/util/ProductContentUtils.java
  marketplace-service/src/main/java/com/axonivy/market/util/VersionUtils.java
  marketplace-service/src/test/java/com/axonivy/market/BaseSetup.java
  marketplace-service/src/test/java/com/axonivy/market/bo/ArtifactTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ExternalDocumentServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/GHAxonIvyProductRepoServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/MetadataServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductContentServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/VersionServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/util/MavenUtilsTest.java
  marketplace-service/src/test/java/com/axonivy/market/util/MetadataReaderUtilsTest.java
  marketplace-service/src/test/java/com/axonivy/market/util/ProductContentUtilsTest.java
Labels: bug

#318 MARP-2189 Fix Lazy loading when Schedule Task start for ProductDepend…
  marketplace-service/src/main/java/com/axonivy/market/repository/ProductDependencyRepository.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/MavenDependencyServiceImpl.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/MavenDependencyServiceImplTest.java
Labels: bug

#321 MARP-2138 Filter text color inconsistent in light mode
  marketplace-ui/src/app/modules/product/product-filter/product-filter.component.html
  marketplace-ui/src/app/modules/product/product-filter/product-filter.component.spec.ts
Labels: bug

#319 MARP-2158 Fix Duplicated snapshot versions in field releasedVersion
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
  marketplace-service/src/test/java/com/axonivy/market/BaseSetup.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductServiceImplTest.java
  marketplace-service/src/test/resources/metadata2.xml
Labels: bug

#322 MARP-2159 Filter sort are wrong after refresh and back to homepage
  marketplace-ui/src/app/modules/product/product.component.spec.ts
  marketplace-ui/src/app/modules/product/product.component.ts
Labels: bug

#323 MARP-2098 Fix recent sorting issue
  marketplace-service/src/main/java/com/axonivy/market/constants/CommonConstants.java
  marketplace-service/src/main/java/com/axonivy/market/repository/impl/CustomProductRepositoryImpl.java
Labels: bug

#324 MARP-2190 Remove marketplace-network to avoid server slowdown after rebuilding
  .github/workflows/docker-build.yml
  marketplace-build/.env
  marketplace-build/README.md
  marketplace-build/config/mongodb/Dockerfile
  marketplace-build/config/mongodb/authen-docker-compose.yml
  marketplace-build/config/mongodb/mongo-init.js
  marketplace-build/config/mongodb/mongod.conf
  marketplace-build/config/mongodb/non-authen-docker-compose.yml
  marketplace-build/dev/.env
  marketplace-build/dev/docker-compose.yml
  marketplace-build/docker-compose.yml
  marketplace-build/release/.env
  marketplace-build/release/docker-compose.yml
  marketplace-service/README.md
  marketplace-service/src/main/resources/application.properties
  marketplace-service/src/test/java/com/axonivy/market/service/impl/SchedulingTasksTest.java
Labels: enhancement

#327 MARP-2160 Missing product's description when switching to old version
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
  marketplace-ui/src/app/modules/release-preview/release-preview.component.ts
Labels: bug

#325 MARP-2202 Add transactional for deleteAllByProductId
  marketplace-service/src/main/java/com/axonivy/market/repository/ProductJsonContentRepository.java
  marketplace-service/src/main/java/com/axonivy/market/repository/ProductModuleContentRepository.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
Labels: bug

#330 MARP-2217 Fixing search API triggered 3 times after enter keyword
  marketplace-ui/src/app/modules/product/product-filter/product-filter.component.ts
Labels: bug

#329 MARP-2080 Download number unrealistic high
  marketplace-service/src/main/java/com/axonivy/market/bo/VersionDownload.java
  marketplace-service/src/main/java/com/axonivy/market/constants/ErrorMessageConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/RequestMappingConstants.java
  marketplace-service/src/main/java/com/axonivy/market/constants/RequestParamConstants.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductDetailsController.java
  marketplace-service/src/main/java/com/axonivy/market/controller/ProductMarketplaceDataController.java
  marketplace-service/src/main/java/com/axonivy/market/repository/ProductDesignerInstallationRepository.java
  marketplace-service/src/main/java/com/axonivy/market/service/ProductContentService.java
  marketplace-service/src/main/java/com/axonivy/market/service/ProductMarketplaceDataService.java
  marketplace-service/src/main/java/com/axonivy/market/service/VersionService.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductContentServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductMarketplaceDataServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/VersionServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/util/AuthorizationUtils.java
  marketplace-service/src/test/java/com/axonivy/market/BaseSetup.java
  marketplace-service/src/test/java/com/axonivy/market/controller/ProductDetailsControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/controller/ProductMarketplaceDataControllerTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductContentServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductMarketplaceDataServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/ProductServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/VersionServiceImplTest.java
  marketplace-service/src/test/java/com/axonivy/market/util/AuthorizationUtilsTest.java
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.html
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.spec.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail-version-action/product-detail-version-action.component.ts
  marketplace-ui/src/app/modules/product/product-detail/product-detail.component.ts
  marketplace-ui/src/app/modules/product/product.service.spec.ts
  marketplace-ui/src/app/modules/product/product.service.ts
  marketplace-ui/src/app/shared/models/version-download.model.ts
  marketplace-ui/src/assets/i18n/de.yaml
  marketplace-ui/src/assets/i18n/en.yaml
Labels: bug

#332 MARP-2137 Skip grant permission for work folder
  marketplace-service/src/main/java/com/axonivy/market/bo/DownloadOption.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ExternalDocumentServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/FileDownloadServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/MavenDependencyServiceImpl.java
  marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductContentServiceImpl.java
  marketplace-service/src/test/java/com/axonivy/market/service/impl/FileDownloadServiceImplTest.java
Labels: bug

#331 MARP-2205 Fix Search/Sort/Filter issues
  marketplace-service/src/main/java/com/axonivy/market/constants/CommonConstants.java
  marketplace-service/src/main/java/com/axonivy/market/entity/Product.java
  marketplace-service/src/main/java/com/axonivy/market/repository/impl/CustomProductRepositoryImpl.java
  marketplace-service/src/test/java/com/axonivy/market/repository/impl/ProductSearchRepositoryImplTest.java
Labels: bug

#333 MARP-2205 Filter/Sort/Search issue - Update test
  marketplace-service/src/test/java/com/axonivy/market/BaseSetup.java
  marketplace-service/src/test/java/com/axonivy/market/repository/impl/ProductSearchRepositoryImplTest.java
Labels: bug, skip-changelog
